# Generated by Django 2.0.7 on 2018-08-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
