# Generated by Django 2.0.7 on 2018-09-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Not Defined', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='Not Defined', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(default='Not Defined', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.CharField(default='Not Defined', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
