# Generated by Django 2.0.7 on 2018-09-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_auto_20180908_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='pack',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shape',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='form',
            field=models.CharField(default='Liquid', max_length=20),
        ),
    ]
